### ISSUE TITLE
如何修改 Cherry Studio 字体

### ISSUE THREAD

**Issue by najoast** [najoast/everything#101]
Cherry Studio 很好用，默认字体也挺好看，但是看久了不免审美疲劳。

当我想要修改字体时，在设置里居然没找到。以前以为这是一个相对较新的软件，由于开发任务太重，官方就是没有提供设置字体的功能的。直到今天我实在无法忍受默认字体，决定向 AI 求助。

Grok 3 给了我答案。

修改方法：
1. 打开 `设置 -> 显示设置 -> 自定义CSS`
2. 添加如下 css 代码 [^1]，把其中的字段改为你想要的:
    ```css
    :root {
      --font-family: 'Segoe UI';
    
      --font-family-serif: 'Segoe UI';
    
      --code-font-family: 'Fira Code', 'Consolas', 'Cascadia Code', Menlo, Courier, monospace;
    }
    ```

`font-family` 和 `font-family-serif` 是非代码字体，`code-font-family` 是代码字体。

**为什么非代码字体有两个？**
如果不想了解细节，可以跳过这段。只需要知道，修改字体时这两个都改就行了。
- **前者是无衬线(Sans-serif)字体**：  
  应用于默认使用无衬线字体的元素，例如：  
  - 未设置字体的 `<button>`、`<input>` 等控件。  
  - CSS 中指定 `font-family: sans-serif;` 的元素。  
  - 大多数现代网页的默认字体（因 Sans-serif 在屏幕上更清晰）。
- **后才是有衬线(Serif)字体**：  
  应用于默认使用衬线字体的元素，例如：  
  - 未设置字体的 `<p>`、`<article>` 等长文本段落。  
  - CSS 中指定 `font-family: serif;` 的元素。
- **注意**：  
  如果网页显式定义了字体（如 `font-family: "Helvetica", sans-serif;`），浏览器会优先使用网页指定的字体。只有当字体不可用且未提供备选时，才会回退到用户设置的 Serif/Sans-serif。

顺便说一句，Cherry 的默认字体比较小，看着挺费劲。如果你想修改字体大小，会发现设置里同样没有。官方的 CSS 样式里也没有设置字体大小的地方。其实想改大小不用动 CSS，直接缩放整个页面就好了，快捷键是：
- 放大 (Zoom In)：`Ctrl + =`
- 缩小 (Zoom Out): `Ctrl + -`

[^1]: [Cherry Studio 源码中的字体预设样式](https://github.com/CherryHQ/cherry-studio/blob/main/src/renderer/src/assets/styles/font.scss)
