### ISSUE TITLE
使用 Docker 部署 Flarum

### ISSUE THREAD

**Issue by najoast** [najoast/everything#12]
# Docker 部署 Flarum
## 1 获取 Flarum 的 Docker 镜像
从 hub.docker.com 拉取：
```
docker pull mondedie/flarum:latest
```

或自己编译：
```
docker build -t mondedie/flarum:latest https://github.com/mondediefr/docker-flarum.git
```

## 2 创建 `docker-compose.yml`
1. 任意找个目录，为了便于管理，最好放到一个有意义的目录内，比如 `~/docker/flarum`。
2. 创建 `docker-compose.yml` 文件，把下面的内容粘贴进去。
3. 把 `/mnt/docker/flarum` 替换为你的目录。
    * 就是第一步里的目录，进到目录后在终端输入 `pwd` 打印出目录的路径。
4. 把 `xxxxxxxxxx` 修改为你想设置的 MySQL 密码。

```yml
version: "3"

services:
  flarum:
    image: mondedie/flarum:stable
    container_name: flarum
    env_file:
      - /mnt/docker/flarum/flarum.env
    volumes:
      - /mnt/docker/flarum/assets:/flarum/app/public/assets
      - /mnt/docker/flarum/extensions:/flarum/app/extensions
      - /mnt/docker/flarum/storage/logs:/flarum/app/storage/logs
      - /mnt/docker/flarum/nginx:/etc/nginx/flarum
    ports:
      - 80:8888
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=xxxxxxxxxx
      - MYSQL_DATABASE=flarum
      - MYSQL_USER=flarum
      - MYSQL_PASSWORD=xxxxxxxxxx
    volumes:
      - /mnt/docker/mysql/db:/var/lib/mysql
   ```

## 3 创建 `flarum.env`
1. 还是在刚才的目录里创建 `flarum.env` 文件，把下面的内容粘贴进去。
2. 修改 `FORUM_URL` 为你自己的IP或域名。注意：
    * 这个值的作用用来标记网站的资源应该从哪里获取，客户端会根据这里配置的值去取对应的资源。
    * 比如假设有一张图，相对路径为 `images/flarum.png`，客户端会根据配置的值拼出绝对路径 `http://domain.tld/images/flarum.png`。
    * 所以这里配你的网站真实能访问的地址
        * 如果没有域名就填IP
        * 如果端口不是80就要填上端口
        * 如果没有 https 就填 http
        * 比如 `http://45.23.89.74:8080`
3. 修改 `DB_PASS=xxxxxxxxxx` 里的密码为你自己的密码。
4. 修改管理员账号信息
    * `FLARUM_ADMIN_PASS=xxxxxxxxxx` 改为你自己的密码
    *  `FLARUM_ADMIN_MAIL=admin@domain.tld` 邮箱改为你自己的真实邮箱，这里一定要用真实邮箱，后面这个就是整个网站的超级管理员账号。
    * `FLARUM_TITLE=Test flarum` 改为网站的真实名字。

## 4 启动
在 `docker-compose.yml` 所在目录内打开终端，运行以下命令启动 Flarum
```
docker-compose up -d
```

以下是一些常用操作：
* 停止并删除：`docker-compose down`
    * 因为所有重要数据都映射出去了，所以可以放心删除窗口

# 安装 PHP 扩展
TODO

# 安装 Flarum 扩展
TODO

# Reference
* https://github.com/mondediefr/docker-flarum?tab=readme-ov-file#installation
