### ISSUE TITLE
Docker-Compose部署SVN服务器

### ISSUE THREAD

**Issue by najoast** [najoast/everything#60]
网上很多手册步骤不全，部署时坑较多。以下是我趟过坑后整理的部署手册。欢迎大家多多交流。

SVN是subversion的缩写，是一个开放源代码的版本控制系统，通过采用分支管理系统的高效管理，简而言之就是用于多个人共同开发同一个项目，实现共享资源，实现最终集中式的管理。

# 1 服务器部署
## 1.1 创建svn挂载目录并授权

创建SVN服务器部署所需目录和文件

```sh
mkdir -p ~/svn/conf
cd ~/svn/conf
mkdir svn_config
mkdir svn_repo
touch svn_config/subversion-access-control
touch svn_config/passwd
chmod 777 -R ~/svn/conf
```

## 1.2 docker-compose 配置

```sh
cd ~/svn
vim docker-compose.yml
```

输入以下内容：
```yml
services:
  svn:
    image: 'elleflorio/svn-server:latest'
    container_name: svn-server
    restart: always
    ports:
      - '3080:80'
      - '3690:3690'
    volumes:
      - './conf/svn_config:/etc/subversion/'
      - './conf/svn_repo:/home/svn'
```

# 2 SVN服务器初始化
## 2.1 创建管理员账户
```sh
docker exec -t svn-server htpasswd -cb /etc/subversion/passwd <username> <password>
```

## 2.2 初始化配置

登录地址：`http://<your_ip>:3080/svnadmin`

注：填写下方红框内容后，运行Test如果提示 `The folder exists but is not writable.`，则需检查上面chmod文件授权命令是否运行。

![Image](https://github.com/user-attachments/assets/7a4201d8-aa91-4a12-b7ed-ed752d10071e)

## 2.3 初始化成功，填入htpasswd创建的账户密码

# 3 SVN日常运维
## 3.1 创建项目库

代码仓库—添加，按要求添加代码库

![Image](https://github.com/user-attachments/assets/d6fdcad2-9125-4c8c-a934-a35d5f505584)

## 3.2 创建用户
用户—添加，创建用户名

![Image](https://github.com/user-attachments/assets/702073f6-107c-4bcc-b9ab-217e50b5d24d)

## 3.3 创建组
组—添加，按要求创建组名

![Image](https://github.com/user-attachments/assets/5ef002c4-9528-4a45-a838-24435cdaa31f)

分配用户到组

组——关系——选择添加到组的用户

![Image](https://github.com/user-attachments/assets/a4bd0f41-3a7c-429c-8f36-b03444e532c9)

## 3.4 授权用户访问权限
访问路径—权限—为用户或组授权访问的项目

![Image](https://github.com/user-attachments/assets/86bccce3-c050-4e85-88ed-487824027475)

## 3.5 创建访问路径
添加项目子目录为访问路径，可以细化文件授权

访问路径—添加—浏览—选中子文件位置，点击子文件前方五角星选中

![Image](https://github.com/user-attachments/assets/c8912a68-2e50-4c49-b1c3-8231f911ba19)

### 3.6.1 使用管理员账户在用户模块里，给user用户分配“用户”角色

![Image](https://github.com/user-attachments/assets/52a353df-4fee-412f-a28b-c060935b1a07)

        

### 3.6.2 用户登录

登录地址：http://172.27.30.94:3080/svnadmin

### 3.6.3 修改用户密码，Session——修改密码

![Image](https://github.com/user-attachments/assets/ebb456ca-a161-4c1e-8095-1b17fcb117ed)

               

# 4 客户端使用
下载并安装TortoiseSVN客户端，创建一个存放文档的文件夹，进入文件夹，右击选择`SVN checkout`，填入版本库URL，格式： `http://IP:Port/svn/仓库名`

客户端使用较为简单，大家可以网上找下相关手册。

版权声明：本文为博主原创文章，遵循 CC 4.0 BY-SA 版权协议，转载请附上原文出处链接和本声明。
原文链接：https://blog.csdn.net/yeqinghanwu/article/details/126984838
